### ISSUE TITLE
Missing validation rules for `type: 'longtext'`

### ISSUE THREAD

**Issue by cspotcode** [balderdashy/anchor#71]
Related to https://github.com/balderdashy/waterline/issues/878

There is no "longtext" validation rule, so when using Waterline with an attribute that is `type: 'longtext'`, it will always fail validation.

This is either a waterline or an anchor bug, or both.

**Comment by dmarcelino** [comment]
This relates to balderdashy/sails-mysql#199 and I believe it's part of a bigger question which is: how should we deal with adapter/DB specific types?

My opinion is, we should allow these to pass through to the adapter while anchor would, for example, treat `longtext` as `string` for any validations.

cc: @particlebanana, @tjwebb

**Comment by cspotcode** [comment]
Anchor should have no knowledge of database types such as "longtext" or
"mediumtext" since it is merely a validation library.  The DB adapter
(sails-mysql) should be converting "mediumtext" into "string" before
passing off to anchor for validation.

Anchor could theoretically validate that "text" does not exceed the maximum
size of 64KB, but that would require that it know the database's character
encoding, too.

Alternatively, "sails-mysql" can register anchor validators for "text",
"mediumtext", etc using `anchor.define()`.  That way, anchor remains
db-agnostic, but we can use `type: "mediumtext"` in our waterline code.

**Comment by dmarcelino** [comment]
#73 should fix the issue. @cspotcode, I would appreciate if you can test my feature branch [dmarcelino:71-longtext](https://github.com/dmarcelino/anchor/tree/71-longtext) and give some feedback.

**Comment by cspotcode** [comment]
Looks good to me.  I unfortunately don't have time to test this, but it looks almost identical to how I solved the problem in our app.  The difference is that I added the "longtext" rule to `types` on each of our waterline collections which used "longtext" columns.

https://github.com/balderdashy/waterline-docs/blob/master/models.md#custom-validations

**Comment by dmarcelino** [comment]
Thanks @tjwebb!
