### ISSUE TITLE
Prepare and release 0.10.3

### ISSUE THREAD

**Issue by dmarcelino** [balderdashy/anchor#76]
There are [12 commits](https://github.com/balderdashy/anchor/compare/0.10.2...master) merged to master since v0.10.2 (Nov 21, 2014) so it's not a bad time to give a glance to pending PRs and release a new version.

Tasks:
- [x] Review and merge/close #75
- [x] Update dependencies #80
- [x] Inspect other [standing pull requests](https://github.com/balderdashy/anchor/pulls)
- [x] Bump package.json version to 0.10.3
- [x] Publish to npm

cc: @particlebanana, @tjwebb

**Comment by devinivy** [comment]
I think #80 should fit in here too.

**Comment by dmarcelino** [comment]
Updated.

**Comment by weyert** [comment]
Could someone do this, Thanks :)

**Comment by particlebanana** [comment]
Yeah I'll get this squared away

**Comment by particlebanana** [comment]
Done
